# Generated by Django 3.2.25 on 2025-09-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakerycategory',
            options={'verbose_name_plural': 'Bakery Categories'},
        ),
        migrations.RenameField(
            model_name='bakerycategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='bakerycategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bakery.bakerycategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='BakerySubCategory',
        ),
    ]
