# Generated by Django 3.2.25 on 2025-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_auto_20250925_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products_subcategories', to='bakery.BakeryCategory'),
        ),
    ]
