# Generated by Django 3.2.25 on 2025-09-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_remove_product_image_productimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'bakery_categories',
            },
        ),
    ]
