# Generated by Django 4.2.20 on 2025-09-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
