# Generated by Django 3.2.25 on 2025-09-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_bakerycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakerySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bakery_subcategories',
            },
        ),
        migrations.RemoveField(
            model_name='bakerycategory',
            name='subcategory_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='bakerysubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bakery.bakerycategory'),
        ),
    ]
