# Generated by Django 3.2.25 on 2025-09-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_form',
            new_name='ContactForm',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bakery.category'),
        ),
    ]
