# Generated by Django 3.2.25 on 2025-09-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_auto_20250919_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerycategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
