# Generated by Django 3.2.25 on 2025-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_bakerycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerycategory',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
