# Generated by Django 3.2.25 on 2025-09-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_alter_bakerycategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerycategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bakery.bakerycategory'),
        ),
    ]
